"""Add 2fa fields to user model

Revision ID: 186464ad2f1c
Revises: 57b85a754b60
Create Date: 2025-06-08 02:32:10.879650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186464ad2f1c'
down_revision = '57b85a754b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('two_factor_enabled')

    # ### end Alembic commands ###
