"""Add OrderBook table

Revision ID: 262b852551a6
Revises: 676815379bd8
Create Date: 2025-05-04 16:46:02.454121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262b852551a6'
down_revision = '676815379bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_asset_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=30, scale=18), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=18), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_book', schema=None) as batch_op:
        batch_op.create_index('idx_order_book_assets', ['base_asset_id', 'quote_asset_id'], unique=False)
        batch_op.create_index('idx_order_book_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_book', schema=None) as batch_op:
        batch_op.drop_index('idx_order_book_status')
        batch_op.drop_index('idx_order_book_assets')

    op.drop_table('order_book')
    # ### end Alembic commands ###
