"""Add image and networks fields to Asset

Revision ID: 5193db8d2f8e
Revises: 597c3853ecd4
Create Date: 2025-05-15 07:57:44.970416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5193db8d2f8e'
down_revision = '597c3853ecd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('networks', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('networks')
        batch_op.drop_column('images')

    # ### end Alembic commands ###
