"""Create tradeorder table

Revision ID: 676815379bd8
Revises: 6bc93b6766a6
Create Date: 2025-05-04 08:47:57.614703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676815379bd8'
down_revision = '6bc93b6766a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_asset_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=30, scale=18), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=18), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_orders')
    # ### end Alembic commands ###
